[package]
name = "lwk_boltz"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
boltz-client = { git = "https://github.com/SatoshiPortal/boltz-rust/", rev = "153d7cd42572f13c08a75ca38e2107ab4034a36b", features = [
    "ws",
] }
lwk_wollet = { version = "0.12.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["rt"] }
log = "0.4"
env_logger = "0.11.8"
thiserror = "1"
bip39 = { version = "2.0.0", features = ["rand"] }

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json"] }
base64 = "0.22"
lwk_signer = { version = "0.12.0" }
lwk_common = { version = "0.12.0" }
