[package]
name = "lwk_boltz"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
boltz-client = { git = "https://github.com/RCasatta/boltz-rust/", rev = "1b213574743d95aa08b0a84682f52f693452eeaf", features = [
    "ws",
    "electrum",
] }
lwk_wollet = { version = "0.12.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["rt"] }
log = "0.4"
env_logger = "0.11.8"
thiserror = "1"
bip39 = { version = "2.0.0", features = ["rand"] }
lightning = { version = "0.1.7", default-features = false }

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json"] }
base64 = "0.22"
lwk_signer = { version = "0.12.0" }
lwk_common = { version = "0.12.0" }
