[package]
name = "lwk_simplicity"
version = "0.15.0"
edition = "2021"
description = "Liquid Wallet Kit - Utilities to deal with Simplicity transactions"
license = "MIT OR BSD-2-Clause"
documentation = "https://docs.rs/lwk_simplicity"

[dependencies]
lwk_common = { version = "0.15.0" }

simplicityhl = { version = "0.4.0" }

thiserror = "2"

[dev-dependencies]
lwk_test_util = { version = "0.15.0"}
lwk_signer = { version = "0.15.0"}
lwk_wollet = { version = "0.15.0"}
